
export const componentFields = /* groq */ `
  isActive,
  "typeComponentValue": typeComponent->value,
  layoutBanner,
  PTextBanner,
  content,
  image,
  backgroundMode,
  responsiveHeight,
  colorWithDarkMode,
  colorBackground1,
  colorBackground2,
  colorBackground3,
  colorBackgroundDark1,
  colorBackgroundDark2,
  colorBackgroundDark3,
  colorBackground1Position,
  colorBackground2Position,
  colorBackground3Position,
  directionDeg,
  imageBackground,
  imageBackgroundType,
  imageBackgroundLayer,
  videoUrl,
  videoType,
  responsiveComponent,
  imagePosition,
  invertLayoutMobile,
  invertLayoutDesk,
  layoutItems,
  PTextItem,
  items[isActive] {
    isActive,
    image,
    icon,
    svgIcon,
    svgIconList,
    alt,
    orderRank,
    content
  }
`;
